development:
  adapter: postgresql
  encoding: unicode
  database: sale_factory_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: sale_factory_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: sale_factory_production
  host: localhost
  pool: 5
  username: postgres
  password: postgres
